### ISSUE TITLE
Package not found on mip 

### ISSUE THREAD

**Issue by tintad** [redoxcode/micropython-servo#1]
Hello

I'm trying to install this package with mip but package is not found.

```
>>> mip.install("micropython-servo")
Installing micropython-servo (latest) from https://micropython.org/pi/v2 to /lib
Package not found: https://micropython.org/pi/v2/package/6/micropython-servo/latest.json
Package may be partially installed
```
Is there anyway that I can install it with package manager

Thanks

**Comment by redoxcode** [comment]
Hello there

This package is not on micropython-lib yet. Only on PyPi.
But I just added a `package.json` file. So you should be able to get it directly from github using:

`mip.install("github:redoxcode/micropython-servo")`

I will look into adding it to micropython-lib soon.

Cheers

**Comment by tintad** [comment]
It works now. Thanks
